baseURL: "https://skidby.netlify.app"
languageCode: "en-GB"
title: "Sayaka Kidby"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "https://twitter.com/sayakidby"
  # github: "#"
  # instagram: "#"
  linkedin: "https://www.linkedin.com/in/sayaka-kidby-8566301aa/?originalSubdomain=uk"
  # dribbble: "#"
  # youtube: "#"
taxonomies:
  author: authors
